#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

    #include "alsa/asoundlib.h"


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 8), // char const *()(snd_seq_t *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // snd_seq_t *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_port_subscribe_t * *)
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 31), // snd_seq_port_subscribe_t * *
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t * *, char const *, int, int)
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 1), // snd_seq_t * *
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const *
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 10 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t *)
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t *, char const *)
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t *, char const *, unsigned int, unsigned int)
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 22 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t *, snd_seq_event_t * *)
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 27 */ _CFFI_OP(_CFFI_OP_POINTER, 46), // snd_seq_event_t * *
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 9), // int()(snd_seq_t *, snd_seq_port_subscribe_t *)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 31 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // snd_seq_port_subscribe_t *
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 56), // void()(snd_seq_port_subscribe_t *, int)
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 31),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 37 */ _CFFI_OP(_CFFI_OP_FUNCTION, 56), // void()(snd_seq_port_subscribe_t *, snd_seq_addr_t const *)
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 31),
/* 39 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // snd_seq_addr_t const *
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 42 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum snd_seq_event_type
/* 43 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // snd_seq_addr_t
/* 44 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // snd_seq_ev_ctrl_t
/* 45 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // snd_seq_ev_note_t
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // snd_seq_event_t *
/* 47 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // snd_seq_event_t
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // snd_seq_port_subscribe_t
/* 49 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // snd_seq_real_time_t
/* 50 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // snd_seq_t
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // snd_seq_timestamp_t
/* 52 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // union $1
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 4), // unsigned char
/* 54 */ _CFFI_OP(_CFFI_OP_ARRAY, 53), // unsigned char[3]
/* 55 */ (_cffi_opcode_t)(3),
/* 56 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_SND_SEQ_EVENT_NOTE(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_NOTE) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_NOTE) | 0);  /* check that SND_SEQ_EVENT_NOTE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_NOTEON(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_NOTEON) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_NOTEON) | 0);  /* check that SND_SEQ_EVENT_NOTEON is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_NOTEOFF(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_NOTEOFF) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_NOTEOFF) | 0);  /* check that SND_SEQ_EVENT_NOTEOFF is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_KEYPRESS(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_KEYPRESS) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_KEYPRESS) | 0);  /* check that SND_SEQ_EVENT_KEYPRESS is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_CONTROLLER(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_CONTROLLER) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_CONTROLLER) | 0);  /* check that SND_SEQ_EVENT_CONTROLLER is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_PGMCHANGE(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_PGMCHANGE) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_PGMCHANGE) | 0);  /* check that SND_SEQ_EVENT_PGMCHANGE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_CHANPRESS(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_CHANPRESS) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_CHANPRESS) | 0);  /* check that SND_SEQ_EVENT_CHANPRESS is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_PITCHBEND(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_PITCHBEND) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_PITCHBEND) | 0);  /* check that SND_SEQ_EVENT_PITCHBEND is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_CONTROL14(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_CONTROL14) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_CONTROL14) | 0);  /* check that SND_SEQ_EVENT_CONTROL14 is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_NONREGPARAM(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_NONREGPARAM) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_NONREGPARAM) | 0);  /* check that SND_SEQ_EVENT_NONREGPARAM is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_EVENT_REGPARAM(unsigned long long *o)
{
  int n = (SND_SEQ_EVENT_REGPARAM) <= 0;
  *o = (unsigned long long)((SND_SEQ_EVENT_REGPARAM) | 0);  /* check that SND_SEQ_EVENT_REGPARAM is an integer */
  return n;
}

static int _cffi_d_snd_seq_client_id(snd_seq_t * x0)
{
  return snd_seq_client_id(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_client_id(PyObject *self, PyObject *arg0)
{
  snd_seq_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_client_id(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_client_id _cffi_d_snd_seq_client_id
#endif

static int _cffi_d_snd_seq_create_simple_port(snd_seq_t * x0, char const * x1, unsigned int x2, unsigned int x3)
{
  return snd_seq_create_simple_port(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_create_simple_port(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  char const * x1;
  unsigned int x2;
  unsigned int x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "snd_seq_create_simple_port", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, unsigned int);
  if (x2 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, unsigned int);
  if (x3 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_create_simple_port(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_create_simple_port _cffi_d_snd_seq_create_simple_port
#endif

static int _cffi_d_snd_seq_event_input(snd_seq_t * x0, snd_seq_event_t * * x1)
{
  return snd_seq_event_input(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_event_input(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  snd_seq_event_t * * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_event_input", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(27), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_event_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(27), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_event_input(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_event_input _cffi_d_snd_seq_event_input
#endif

static int _cffi_d_snd_seq_get_port_subscription(snd_seq_t * x0, snd_seq_port_subscribe_t * x1)
{
  return snd_seq_get_port_subscription(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_get_port_subscription(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  snd_seq_port_subscribe_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_get_port_subscription", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_get_port_subscription(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_get_port_subscription _cffi_d_snd_seq_get_port_subscription
#endif

static char const * _cffi_d_snd_seq_name(snd_seq_t * x0)
{
  return snd_seq_name(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_name(PyObject *self, PyObject *arg0)
{
  snd_seq_t * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  char const * result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_name(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(8));
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_name _cffi_d_snd_seq_name
#endif

static int _cffi_d_snd_seq_open(snd_seq_t * * x0, char const * x1, int x2, int x3)
{
  return snd_seq_open(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_open(PyObject *self, PyObject *args)
{
  snd_seq_t * * x0;
  char const * x1;
  int x2;
  int x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "snd_seq_open", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(7), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(7), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_open(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_open _cffi_d_snd_seq_open
#endif

static int _cffi_d_snd_seq_port_subscribe_malloc(snd_seq_port_subscribe_t * * x0)
{
  return snd_seq_port_subscribe_malloc(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_malloc(PyObject *self, PyObject *arg0)
{
  snd_seq_port_subscribe_t * * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(4), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_port_subscribe_malloc(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_malloc _cffi_d_snd_seq_port_subscribe_malloc
#endif

static void _cffi_d_snd_seq_port_subscribe_set_dest(snd_seq_port_subscribe_t * x0, snd_seq_addr_t const * x1)
{
  snd_seq_port_subscribe_set_dest(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_dest(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  snd_seq_addr_t const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_dest", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_addr_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_dest(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_dest _cffi_d_snd_seq_port_subscribe_set_dest
#endif

static void _cffi_d_snd_seq_port_subscribe_set_exclusive(snd_seq_port_subscribe_t * x0, int x1)
{
  snd_seq_port_subscribe_set_exclusive(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_exclusive(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_exclusive", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_exclusive(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_exclusive _cffi_d_snd_seq_port_subscribe_set_exclusive
#endif

static void _cffi_d_snd_seq_port_subscribe_set_queue(snd_seq_port_subscribe_t * x0, int x1)
{
  snd_seq_port_subscribe_set_queue(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_queue(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_queue", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_queue(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_queue _cffi_d_snd_seq_port_subscribe_set_queue
#endif

static void _cffi_d_snd_seq_port_subscribe_set_sender(snd_seq_port_subscribe_t * x0, snd_seq_addr_t const * x1)
{
  snd_seq_port_subscribe_set_sender(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_sender(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  snd_seq_addr_t const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_sender", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_addr_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_sender(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_sender _cffi_d_snd_seq_port_subscribe_set_sender
#endif

static void _cffi_d_snd_seq_port_subscribe_set_time_real(snd_seq_port_subscribe_t * x0, int x1)
{
  snd_seq_port_subscribe_set_time_real(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_time_real(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_time_real", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_time_real(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_time_real _cffi_d_snd_seq_port_subscribe_set_time_real
#endif

static void _cffi_d_snd_seq_port_subscribe_set_time_update(snd_seq_port_subscribe_t * x0, int x1)
{
  snd_seq_port_subscribe_set_time_update(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_port_subscribe_set_time_update(PyObject *self, PyObject *args)
{
  snd_seq_port_subscribe_t * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_port_subscribe_set_time_update", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { snd_seq_port_subscribe_set_time_update(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_snd_seq_port_subscribe_set_time_update _cffi_d_snd_seq_port_subscribe_set_time_update
#endif

static int _cffi_d_snd_seq_set_client_name(snd_seq_t * x0, char const * x1)
{
  return snd_seq_set_client_name(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_set_client_name(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  char const * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_set_client_name", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(8), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_set_client_name(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_set_client_name _cffi_d_snd_seq_set_client_name
#endif

static int _cffi_d_snd_seq_subscribe_port(snd_seq_t * x0, snd_seq_port_subscribe_t * x1)
{
  return snd_seq_subscribe_port(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_subscribe_port(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  snd_seq_port_subscribe_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_subscribe_port", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_subscribe_port(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_subscribe_port _cffi_d_snd_seq_subscribe_port
#endif

static int _cffi_d_snd_seq_unsubscribe_port(snd_seq_t * x0, snd_seq_port_subscribe_t * x1)
{
  return snd_seq_unsubscribe_port(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_snd_seq_unsubscribe_port(PyObject *self, PyObject *args)
{
  snd_seq_t * x0;
  snd_seq_port_subscribe_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "snd_seq_unsubscribe_port", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (snd_seq_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(31), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (snd_seq_port_subscribe_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(31), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = snd_seq_unsubscribe_port(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_snd_seq_unsubscribe_port _cffi_d_snd_seq_unsubscribe_port
#endif

static int _cffi_const_SND_SEQ_OPEN_DUPLEX(unsigned long long *o)
{
  int n = (SND_SEQ_OPEN_DUPLEX) <= 0;
  *o = (unsigned long long)((SND_SEQ_OPEN_DUPLEX) | 0);  /* check that SND_SEQ_OPEN_DUPLEX is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_OPEN_INPUT(unsigned long long *o)
{
  int n = (SND_SEQ_OPEN_INPUT) <= 0;
  *o = (unsigned long long)((SND_SEQ_OPEN_INPUT) | 0);  /* check that SND_SEQ_OPEN_INPUT is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_OPEN_OUTPUT(unsigned long long *o)
{
  int n = (SND_SEQ_OPEN_OUTPUT) <= 0;
  *o = (unsigned long long)((SND_SEQ_OPEN_OUTPUT) | 0);  /* check that SND_SEQ_OPEN_OUTPUT is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_DUPLEX(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_DUPLEX) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_DUPLEX) | 0);  /* check that SND_SEQ_PORT_CAP_DUPLEX is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_NO_EXPORT(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_NO_EXPORT) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_NO_EXPORT) | 0);  /* check that SND_SEQ_PORT_CAP_NO_EXPORT is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_READ(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_READ) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_READ) | 0);  /* check that SND_SEQ_PORT_CAP_READ is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_SUBS_READ(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_SUBS_READ) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_SUBS_READ) | 0);  /* check that SND_SEQ_PORT_CAP_SUBS_READ is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_SUBS_WRITE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_SUBS_WRITE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_SUBS_WRITE) | 0);  /* check that SND_SEQ_PORT_CAP_SUBS_WRITE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_SYNC_READ(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_SYNC_READ) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_SYNC_READ) | 0);  /* check that SND_SEQ_PORT_CAP_SYNC_READ is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_SYNC_WRITE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_SYNC_WRITE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_SYNC_WRITE) | 0);  /* check that SND_SEQ_PORT_CAP_SYNC_WRITE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_CAP_WRITE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_CAP_WRITE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_CAP_WRITE) | 0);  /* check that SND_SEQ_PORT_CAP_WRITE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_SYSTEM_ANNOUNCE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_SYSTEM_ANNOUNCE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_SYSTEM_ANNOUNCE) | 0);  /* check that SND_SEQ_PORT_SYSTEM_ANNOUNCE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_SYSTEM_TIMER(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_SYSTEM_TIMER) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_SYSTEM_TIMER) | 0);  /* check that SND_SEQ_PORT_SYSTEM_TIMER is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_APPLICATION(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_APPLICATION) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_APPLICATION) | 0);  /* check that SND_SEQ_PORT_TYPE_APPLICATION is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_DIRECT_SAMPLE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_DIRECT_SAMPLE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_DIRECT_SAMPLE) | 0);  /* check that SND_SEQ_PORT_TYPE_DIRECT_SAMPLE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_HARDWARE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_HARDWARE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_HARDWARE) | 0);  /* check that SND_SEQ_PORT_TYPE_HARDWARE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_GENERIC(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_GENERIC) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_GENERIC) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_GENERIC is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_GM(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_GM) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_GM) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_GM is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_GM2(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_GM2) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_GM2) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_GM2 is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_GS(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_GS) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_GS) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_GS is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_MT32(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_MT32) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_MT32) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_MT32 is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_MIDI_XG(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_MIDI_XG) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_MIDI_XG) | 0);  /* check that SND_SEQ_PORT_TYPE_MIDI_XG is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_PORT(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_PORT) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_PORT) | 0);  /* check that SND_SEQ_PORT_TYPE_PORT is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_SAMPLE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_SAMPLE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_SAMPLE) | 0);  /* check that SND_SEQ_PORT_TYPE_SAMPLE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_SOFTWARE(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_SOFTWARE) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_SOFTWARE) | 0);  /* check that SND_SEQ_PORT_TYPE_SOFTWARE is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_SPECIFIC(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_SPECIFIC) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_SPECIFIC) | 0);  /* check that SND_SEQ_PORT_TYPE_SPECIFIC is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_SYNTH(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_SYNTH) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_SYNTH) | 0);  /* check that SND_SEQ_PORT_TYPE_SYNTH is an integer */
  return n;
}

static int _cffi_const_SND_SEQ_PORT_TYPE_SYNTHESIZER(unsigned long long *o)
{
  int n = (SND_SEQ_PORT_TYPE_SYNTHESIZER) <= 0;
  *o = (unsigned long long)((SND_SEQ_PORT_TYPE_SYNTHESIZER) | 0);  /* check that SND_SEQ_PORT_TYPE_SYNTHESIZER is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_addr_t(snd_seq_addr_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->client) | 0);  /* check that 'snd_seq_addr_t.client' is an integer */
  (void)((p->port) | 0);  /* check that 'snd_seq_addr_t.port' is an integer */
}
struct _cffi_align__snd_seq_addr_t { char x; snd_seq_addr_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_ev_ctrl_t(snd_seq_ev_ctrl_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->channel) | 0);  /* check that 'snd_seq_ev_ctrl_t.channel' is an integer */
  { unsigned char(*tmp)[3] = &p->unused; (void)tmp; }
  (void)((p->param) | 0);  /* check that 'snd_seq_ev_ctrl_t.param' is an integer */
  (void)((p->value) | 0);  /* check that 'snd_seq_ev_ctrl_t.value' is an integer */
}
struct _cffi_align__snd_seq_ev_ctrl_t { char x; snd_seq_ev_ctrl_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_ev_note_t(snd_seq_ev_note_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->channel) | 0);  /* check that 'snd_seq_ev_note_t.channel' is an integer */
  (void)((p->note) | 0);  /* check that 'snd_seq_ev_note_t.note' is an integer */
  (void)((p->velocity) | 0);  /* check that 'snd_seq_ev_note_t.velocity' is an integer */
  (void)((p->off_velocity) | 0);  /* check that 'snd_seq_ev_note_t.off_velocity' is an integer */
  (void)((p->duration) | 0);  /* check that 'snd_seq_ev_note_t.duration' is an integer */
}
struct _cffi_align__snd_seq_ev_note_t { char x; snd_seq_ev_note_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_event_t(snd_seq_event_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->type) | 0);  /* check that 'snd_seq_event_t.type' is an integer */
  (void)((p->flags) | 0);  /* check that 'snd_seq_event_t.flags' is an integer */
  (void)((p->tag) | 0);  /* check that 'snd_seq_event_t.tag' is an integer */
  (void)((p->queue) | 0);  /* check that 'snd_seq_event_t.queue' is an integer */
  { snd_seq_timestamp_t *tmp = &p->time; (void)tmp; }
  { snd_seq_addr_t *tmp = &p->source; (void)tmp; }
  { snd_seq_addr_t *tmp = &p->dest; (void)tmp; }
  /* cannot generate 'union $1' in field 'data': unknown type name */
}
struct _cffi_align__snd_seq_event_t { char x; snd_seq_event_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_real_time_t(snd_seq_real_time_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->tv_sec) | 0);  /* check that 'snd_seq_real_time_t.tv_sec' is an integer */
  (void)((p->tv_nsec) | 0);  /* check that 'snd_seq_real_time_t.tv_nsec' is an integer */
}
struct _cffi_align__snd_seq_real_time_t { char x; snd_seq_real_time_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__snd_seq_timestamp_t(snd_seq_timestamp_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->tick) | 0);  /* check that 'snd_seq_timestamp_t.tick' is an integer */
  { snd_seq_real_time_t *tmp = &p->time; (void)tmp; }
}
struct _cffi_align__snd_seq_timestamp_t { char x; snd_seq_timestamp_t y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "SND_SEQ_EVENT_CHANPRESS", (void *)_cffi_const_SND_SEQ_EVENT_CHANPRESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_CONTROL14", (void *)_cffi_const_SND_SEQ_EVENT_CONTROL14, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_CONTROLLER", (void *)_cffi_const_SND_SEQ_EVENT_CONTROLLER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_KEYPRESS", (void *)_cffi_const_SND_SEQ_EVENT_KEYPRESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_NONREGPARAM", (void *)_cffi_const_SND_SEQ_EVENT_NONREGPARAM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_NOTE", (void *)_cffi_const_SND_SEQ_EVENT_NOTE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_NOTEOFF", (void *)_cffi_const_SND_SEQ_EVENT_NOTEOFF, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_NOTEON", (void *)_cffi_const_SND_SEQ_EVENT_NOTEON, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_PGMCHANGE", (void *)_cffi_const_SND_SEQ_EVENT_PGMCHANGE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_PITCHBEND", (void *)_cffi_const_SND_SEQ_EVENT_PITCHBEND, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_EVENT_REGPARAM", (void *)_cffi_const_SND_SEQ_EVENT_REGPARAM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SND_SEQ_OPEN_DUPLEX", (void *)_cffi_const_SND_SEQ_OPEN_DUPLEX, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_OPEN_INPUT", (void *)_cffi_const_SND_SEQ_OPEN_INPUT, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_OPEN_OUTPUT", (void *)_cffi_const_SND_SEQ_OPEN_OUTPUT, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_DUPLEX", (void *)_cffi_const_SND_SEQ_PORT_CAP_DUPLEX, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_NO_EXPORT", (void *)_cffi_const_SND_SEQ_PORT_CAP_NO_EXPORT, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_READ", (void *)_cffi_const_SND_SEQ_PORT_CAP_READ, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_SUBS_READ", (void *)_cffi_const_SND_SEQ_PORT_CAP_SUBS_READ, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_SUBS_WRITE", (void *)_cffi_const_SND_SEQ_PORT_CAP_SUBS_WRITE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_SYNC_READ", (void *)_cffi_const_SND_SEQ_PORT_CAP_SYNC_READ, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_SYNC_WRITE", (void *)_cffi_const_SND_SEQ_PORT_CAP_SYNC_WRITE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_CAP_WRITE", (void *)_cffi_const_SND_SEQ_PORT_CAP_WRITE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_SYSTEM_ANNOUNCE", (void *)_cffi_const_SND_SEQ_PORT_SYSTEM_ANNOUNCE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_SYSTEM_TIMER", (void *)_cffi_const_SND_SEQ_PORT_SYSTEM_TIMER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_APPLICATION", (void *)_cffi_const_SND_SEQ_PORT_TYPE_APPLICATION, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_DIRECT_SAMPLE", (void *)_cffi_const_SND_SEQ_PORT_TYPE_DIRECT_SAMPLE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_HARDWARE", (void *)_cffi_const_SND_SEQ_PORT_TYPE_HARDWARE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_GENERIC", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_GENERIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_GM", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_GM, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_GM2", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_GM2, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_GS", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_GS, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_MT32", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_MT32, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_MIDI_XG", (void *)_cffi_const_SND_SEQ_PORT_TYPE_MIDI_XG, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_PORT", (void *)_cffi_const_SND_SEQ_PORT_TYPE_PORT, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_SAMPLE", (void *)_cffi_const_SND_SEQ_PORT_TYPE_SAMPLE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_SOFTWARE", (void *)_cffi_const_SND_SEQ_PORT_TYPE_SOFTWARE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_SPECIFIC", (void *)_cffi_const_SND_SEQ_PORT_TYPE_SPECIFIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_SYNTH", (void *)_cffi_const_SND_SEQ_PORT_TYPE_SYNTH, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SND_SEQ_PORT_TYPE_SYNTHESIZER", (void *)_cffi_const_SND_SEQ_PORT_TYPE_SYNTHESIZER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "snd_seq_client_id", (void *)_cffi_f_snd_seq_client_id, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 12), (void *)_cffi_d_snd_seq_client_id },
  { "snd_seq_create_simple_port", (void *)_cffi_f_snd_seq_create_simple_port, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 19), (void *)_cffi_d_snd_seq_create_simple_port },
  { "snd_seq_event_input", (void *)_cffi_f_snd_seq_event_input, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 25), (void *)_cffi_d_snd_seq_event_input },
  { "snd_seq_get_port_subscription", (void *)_cffi_f_snd_seq_get_port_subscription, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_snd_seq_get_port_subscription },
  { "snd_seq_name", (void *)_cffi_f_snd_seq_name, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_snd_seq_name },
  { "snd_seq_open", (void *)_cffi_f_snd_seq_open, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_snd_seq_open },
  { "snd_seq_port_subscribe_malloc", (void *)_cffi_f_snd_seq_port_subscribe_malloc, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 3), (void *)_cffi_d_snd_seq_port_subscribe_malloc },
  { "snd_seq_port_subscribe_set_dest", (void *)_cffi_f_snd_seq_port_subscribe_set_dest, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_snd_seq_port_subscribe_set_dest },
  { "snd_seq_port_subscribe_set_exclusive", (void *)_cffi_f_snd_seq_port_subscribe_set_exclusive, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_snd_seq_port_subscribe_set_exclusive },
  { "snd_seq_port_subscribe_set_queue", (void *)_cffi_f_snd_seq_port_subscribe_set_queue, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_snd_seq_port_subscribe_set_queue },
  { "snd_seq_port_subscribe_set_sender", (void *)_cffi_f_snd_seq_port_subscribe_set_sender, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 37), (void *)_cffi_d_snd_seq_port_subscribe_set_sender },
  { "snd_seq_port_subscribe_set_time_real", (void *)_cffi_f_snd_seq_port_subscribe_set_time_real, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_snd_seq_port_subscribe_set_time_real },
  { "snd_seq_port_subscribe_set_time_update", (void *)_cffi_f_snd_seq_port_subscribe_set_time_update, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 33), (void *)_cffi_d_snd_seq_port_subscribe_set_time_update },
  { "snd_seq_set_client_name", (void *)_cffi_f_snd_seq_set_client_name, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 15), (void *)_cffi_d_snd_seq_set_client_name },
  { "snd_seq_subscribe_port", (void *)_cffi_f_snd_seq_subscribe_port, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_snd_seq_subscribe_port },
  { "snd_seq_unsubscribe_port", (void *)_cffi_f_snd_seq_unsubscribe_port, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_snd_seq_unsubscribe_port },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "client", offsetof(snd_seq_addr_t, client),
              sizeof(((snd_seq_addr_t *)0)->client),
              _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "port", offsetof(snd_seq_addr_t, port),
            sizeof(((snd_seq_addr_t *)0)->port),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "channel", offsetof(snd_seq_ev_ctrl_t, channel),
               sizeof(((snd_seq_ev_ctrl_t *)0)->channel),
               _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "unused", offsetof(snd_seq_ev_ctrl_t, unused),
              sizeof(((snd_seq_ev_ctrl_t *)0)->unused),
              _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "param", offsetof(snd_seq_ev_ctrl_t, param),
             sizeof(((snd_seq_ev_ctrl_t *)0)->param),
             _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "value", offsetof(snd_seq_ev_ctrl_t, value),
             sizeof(((snd_seq_ev_ctrl_t *)0)->value),
             _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "channel", offsetof(snd_seq_ev_note_t, channel),
               sizeof(((snd_seq_ev_note_t *)0)->channel),
               _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "note", offsetof(snd_seq_ev_note_t, note),
            sizeof(((snd_seq_ev_note_t *)0)->note),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "velocity", offsetof(snd_seq_ev_note_t, velocity),
                sizeof(((snd_seq_ev_note_t *)0)->velocity),
                _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "off_velocity", offsetof(snd_seq_ev_note_t, off_velocity),
                    sizeof(((snd_seq_ev_note_t *)0)->off_velocity),
                    _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "duration", offsetof(snd_seq_ev_note_t, duration),
                sizeof(((snd_seq_ev_note_t *)0)->duration),
                _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "type", offsetof(snd_seq_event_t, type),
            sizeof(((snd_seq_event_t *)0)->type),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "flags", offsetof(snd_seq_event_t, flags),
             sizeof(((snd_seq_event_t *)0)->flags),
             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "tag", offsetof(snd_seq_event_t, tag),
           sizeof(((snd_seq_event_t *)0)->tag),
           _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "queue", offsetof(snd_seq_event_t, queue),
             sizeof(((snd_seq_event_t *)0)->queue),
             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "time", offsetof(snd_seq_event_t, time),
            sizeof(((snd_seq_event_t *)0)->time),
            _CFFI_OP(_CFFI_OP_NOOP, 51) },
  { "source", offsetof(snd_seq_event_t, source),
              sizeof(((snd_seq_event_t *)0)->source),
              _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "dest", offsetof(snd_seq_event_t, dest),
            sizeof(((snd_seq_event_t *)0)->dest),
            _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "data", offsetof(snd_seq_event_t, data),
            sizeof(((snd_seq_event_t *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "tv_sec", offsetof(snd_seq_real_time_t, tv_sec),
              sizeof(((snd_seq_real_time_t *)0)->tv_sec),
              _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "tv_nsec", offsetof(snd_seq_real_time_t, tv_nsec),
               sizeof(((snd_seq_real_time_t *)0)->tv_nsec),
               _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "tick", offsetof(snd_seq_timestamp_t, tick),
            sizeof(((snd_seq_timestamp_t *)0)->tick),
            _CFFI_OP(_CFFI_OP_NOOP, 22) },
  { "time", offsetof(snd_seq_timestamp_t, time),
            sizeof(((snd_seq_timestamp_t *)0)->time),
            _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "note", (size_t)-1,
            (size_t)-1,
            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "control", (size_t)-1,
               (size_t)-1,
               _CFFI_OP(_CFFI_OP_NOOP, 44) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$1", 52, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 23, 2 /* unnamed */ },
  { "$snd_seq_port_subscribe_t", 48, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "$snd_seq_t", 50, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "snd_seq_addr", 43, _CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_addr_t), offsetof(struct _cffi_align__snd_seq_addr_t, y), 0, 2 },
  { "snd_seq_ev_ctrl", 44, _CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_ev_ctrl_t), offsetof(struct _cffi_align__snd_seq_ev_ctrl_t, y), 2, 4 },
  { "snd_seq_ev_note", 45, _CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_ev_note_t), offsetof(struct _cffi_align__snd_seq_ev_note_t, y), 6, 5 },
  { "snd_seq_event", 47, _CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_event_t), offsetof(struct _cffi_align__snd_seq_event_t, y), 11, 8 },
  { "snd_seq_real_time", 49, _CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_real_time_t), offsetof(struct _cffi_align__snd_seq_real_time_t, y), 19, 2 },
  { "snd_seq_timestamp", 51, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    sizeof(snd_seq_timestamp_t), offsetof(struct _cffi_align__snd_seq_timestamp_t, y), 21, 2 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "snd_seq_event_type", 42, _cffi_prim_int(sizeof(enum snd_seq_event_type), ((enum snd_seq_event_type)-1) <= 0),
    "SND_SEQ_EVENT_NOTE,SND_SEQ_EVENT_NOTEON,SND_SEQ_EVENT_NOTEOFF,SND_SEQ_EVENT_KEYPRESS,SND_SEQ_EVENT_CONTROLLER,SND_SEQ_EVENT_PGMCHANGE,SND_SEQ_EVENT_CHANPRESS,SND_SEQ_EVENT_PITCHBEND,SND_SEQ_EVENT_CONTROL14,SND_SEQ_EVENT_NONREGPARAM,SND_SEQ_EVENT_REGPARAM" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "snd_seq_addr_t", 43 },
  { "snd_seq_ev_ctrl_t", 44 },
  { "snd_seq_ev_note_t", 45 },
  { "snd_seq_event_t", 47 },
  { "snd_seq_event_type_t", 53 },
  { "snd_seq_port_subscribe_t", 48 },
  { "snd_seq_real_time_t", 49 },
  { "snd_seq_t", 50 },
  { "snd_seq_tick_time_t", 22 },
  { "snd_seq_timestamp_t", 51 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  55,  /* num_globals */
  9,  /* num_struct_unions */
  1,  /* num_enums */
  10,  /* num_typenames */
  NULL,  /* no includes */
  57,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__asound(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__asound(void) { return NULL; }
#  else
     init_asound(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__asound(void)
{
  return _cffi_init("asound._asound", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_asound(void)
{
  _cffi_init("asound._asound", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
